name: Scrape Sreality

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6 AM UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Get current date
        id: vars
        run: echo "date=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python main.py

      - name: Upload SQLite DB as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sreality-scrape-${{ steps.vars.outputs.date }}
          path: data/sreality_data.db
