name: Test Scraper Date Naming

on:
  workflow_dispatch:  # <-- this enables manual runs via GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get current date
        id: vars
        run: echo "date=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT

      - name: Debug date output
        run: echo "Artifact name will be: sreality-scrape-${{ steps.vars.outputs.date }}"

      - name: Create dummy DB file
        run: |
          mkdir -p data
          echo "test" > data/sreality_data.db

      - name: Upload dummy artifact
        uses: actions/upload-artifact@v4
        with:
          name: sreality-scrape-${{ steps.vars.outputs.date }}
          path: data/sreality_data.db
